#!/bin/sh 
#
#  Install
###########################################################################
#
#  Purpose:
#
#  Usage:  Install
#
###########################################################################

cd `dirname $0`

if [ ! -r Configuration ]
then
    echo "Cannot read Configuration file." | tee -a ${LOG}
    exit 1
fi

MGIGFFHOME=`pwd`
export MGIGFFHOME

cat > ${MGIGFFHOME}/mgigff.sh << EOF
#!/bin/sh
MGIGFFHOME=${MGIGFFHOME}
export MGIGFFHOME
. \${MGIGFFHOME}/Configuration
\${PYTHON} \${MGIGFFHOME}/bin/mgigff.py \$*

EOF

chmod 555 ${MGIGFFHOME}/mgigff.sh

echo "Installation successful."
exit 0

